language: ruby
rvm:
- 2.2.2
env:
  global:
  - secure: F6Jf+eRauX2w9amT3t0bNc2VIH2fGQud5omHAQ3JnfXS+9odjyeVQcKfNXrOZUXaa2ArKy24/iGWDk+tWOZ+YHZ5FT36MVx1Sk8x5PLN8Ncl8NSnzjPQfSYXV8TyuR492HWW+8auX80bNLFpxIQJYMHYSRBUaE83zlUNq1p5J4M=
  - secure: Nou4FwegNCBBITGlplxWq34CMbZpBVOAwEM2NK75FcG6pKVA3u/YqkSb/o7AsuRgfnbk6C78s16yXv8rOCBPBqPQEe3nUWSlRRAMNEZ4srf/v1EbM+ywapwUxCX/mmR1q5k6sX3YnFiegW7i6ZQJLRU/zZhbN+OL6X35P6VH0/4=
  - secure: Ks1cvFwADDJaHMsK/kO94QnmhP0ly5GbFDEI9hs1MpkkmMQRsFQ/dt9jkGd06jnLgS0MaMiKXfX/LBYiFx/6RORNe/u03GVlrwiDuWYaiU9k2bzhulWAb9FbHS88+GwW7n1nYV55xfYwXQyC2z20Jhzt1DeOREM0OCckfJnhgRo=
